### ISSUE TITLE
Naming an argument 'query' results in exception when parsing the GraphQL query

### ISSUE THREAD

**Issue by stijnopheide** [walmartlabs/lacinia#104]
When a query accepts an argument with the name `query` it's not parseable.

## Minimal Example to reproduce the error

This test has been run on `0.19.0`

### Working

```clojure
(def good-schema
  (com.walmartlabs.lacinia.schema/compile
    {:objects {:QueryResult {:fields {:result {:type 'String}}}}
     :queries {:someQuery {:type    :QueryResult
                           :args    {:q {:type 'String}}
                           :resolve (fn [ctx args v]
                                      {:result (:q args)})}}}))

(com.walmartlabs.lacinia.parser/parse-query good-schema "query DoQuery {someQuery(q: \"lala\") {result}}")
;; => no exception
```

### Not Working

```clojure
(def bad-schema
  (com.walmartlabs.lacinia.schema/compile
    {:objects {:QueryResult {:fields {:result {:type 'String}}}}
     :queries {:someQuery {:type    :QueryResult
                           :args    {:query {:type 'String}}
                           :resolve (fn [ctx args v]
                                      {:result (:query args)})}}}))

(com.walmartlabs.lacinia.parser/parse-query bad-schema "query DoQuery {someQuery(query: \"lala\") {result}}")
```

The only difference between `good-schema` and `bad-schema` is the name of the argument `q` versus `query`.

GraphiQL thinks it's ok, and as far as I understand the [spec](https://facebook.github.io/graphql/#sec-Names) says that the keys of Argument have to be of type 'Name', which doesn't forbid the specific string `query`.

**Comment by hlship** [comment]
In our grammar, `query` is a reserved word.  I'll check the spec to see if there's anything similar. If not, we'll have to figure out how to convince the parser to accept the value there.

By "not working" do you mean that you get an exception or a parse error, or what?

**Comment by hlship** [comment]
```
clojure.lang.ExceptionInfo: Failed to parse GraphQL query.
                            clojure.core/eval    core.clj: 3105
                                          ...                  
                                user/eval6250   REPL Input     
   com.walmartlabs.lacinia.parser/parse-query  parser.clj: 1221
   com.walmartlabs.lacinia.parser/parse-query  parser.clj: 1227
com.walmartlabs.lacinia.parser/parse-query/fn  parser.clj: 1231
                         clojure.core/ex-info    core.clj: 4617
clojure.lang.ExceptionInfo: Failed to parse GraphQL query.
    errors: ({:location {:line 1, :column nil},
              :parse-error "mismatched input 'query' expecting Name"}
             {:location {:line 1, :column nil},
              :parse-error "mismatched input ':' expecting {'(', '{', '@', Name}"}
             {:location {:line 1, :column nil},
              :parse-error
              "extraneous input '}' expecting {<EOF>, 'query', 'mutation', 'subscription', '{', 'fragment'}"})
```

**Comment by stijnopheide** [comment]
yes, that's exactly the exception we see.

Also, the workaround is easy, just use another name for the argument. Maybe a mention in the documentation about reserved keywords can avoid confusion for other users for now?

**Comment by hlship** [comment]
True, I'd like to test this against the reference implementation to see if it can accept it.

**Comment by stijnopheide** [comment]
There is another use case in which you will get this exception and this when the query sent by the client will use the word 'query' anywhere in the input objects.

e.g.
```query DoQuery($query: String) {someQuery(q: $query) {result}}```
and the input to that query
```{"query": "lalala"}```

This is I think more problematic because it has nothing to do with the schema and from the clients' perspective the error message is very confusing.

**Comment by hlship** [comment]
Just checked against the RI:

```
var { graphql, buildSchema } = require('graphql');

var schema = buildSchema(`
  type Query {
    query: String
  }
`);

var root = { query: () => 'Hello world!' };

graphql(schema, '{ query }', root).then((response) => {
  console.log(response);
});
```

... and this works as expected.  So `query` is only a "reserved word" when it appears in that location.  I'll have to do some work to figure out how to make this work correctly in Antlr.

**Comment by hlship** [comment]
This one is turning out to be a disproportionate amount of work vs. reward.
