### ISSUE TITLE
String escaping doesn't work

### ISSUE THREAD

**Issue by mullr** [walmartlabs/lacinia#108]
When passing a string as an argument to a query, internal escaping isn't evaluated. 

I wrote a test case here: https://github.com/mullr/lacinia/tree/string-escaping-repro

**Comment by mullr** [comment]
More specifically: https://github.com/mullr/lacinia/blob/string-escaping-repro/test/com/walmartlabs/lacinia/parser_test.clj#L44

**Comment by thorstadt** [comment]
Fixed in #111

**Comment by baldmountain** [comment]
I don't think this is fixed. #111 is isolated to query parsing. The example above is a mutation. I'm currently working around this by url encoding the parameter field (a JSON string filled with double quotes) in the client and url decoding it in the server.

**Comment by thorstadt** [comment]
@baldmountain Lacinia parses queries and mutations the same way, the PR includes a test for this case: https://github.com/walmartlabs/lacinia/pull/111/files#diff-3d2e5adacfff4c8484d5c3a5930edbbeR48

0.21.0, released yesterday, is the first to contain this fix. Are you using that version?

**Comment by baldmountain** [comment]
I'm using lacinia-pedestal so that will need the update from 0.20.0 to o.21.0.
