### ISSUE TITLE
Spec checking wrong for enum default values

### ISSUE THREAD

**Issue by zerg000000** [walmartlabs/lacinia#110]
given that we have schema like

```clojure
{:enums
 {:animal
  {:values [:DOG :CAT]}}
 :objects
 {:thing {:fields {:name {:type String}}
 :queries
 {:search_animal
  {:type (list :thing)
   :args {:animal_type {:type (list :animal)
                                     :default-value [:DOG]} ; this could be either keyword or symbol in the list, but it would be passed as symbol to resolver if we put a symbol in schema.edn
             :another {:type :animal
                             :default-value DOG}}} ; this must be symbol to get pass the spec checking, it would be passed as keyword to resolver
}
```
I think the `default-value` of `(list :animal)` should accept `[:DOG]` and spec should check this.
I think the `default-value` of `:type :animal` should accept `:DOG` and spec should check this.

**Comment by hlship** [comment]
What version of Lacinia are you using?

Performing the checks you describe in spec will make the specs extremely complex; checks such as what you describe have been occurring in code, after a more cursory check via spec.

**Comment by hlship** [comment]
Please reopen when you have additional information.
