### ISSUE TITLE
Failure to merge sub-fields inside fragments

### ISSUE THREAD

**Issue by gusbicalho** [walmartlabs/lacinia#118]
Basically, queries like the one below don't work - the result (if the hero is a droid) should contain both the best_friend's name and forceSide, but as of https://github.com/walmartlabs/lacinia/commit/52850e170a1fcfa2d536fb7ee632a1ca90a01e08, only the best_friend's name is returned.
I've written test cases to reproduce the issue in #117

```graphql
query {
  hero {
    best_friend {
      name
      forceSide {
        name
      }
    }
    ...on droid {
      best_friend {
        name
      }
    }
  }
}
```

```graphql
query {
  hero {
    ...DroidWithBestFriendNameAndForceSide
    ...DroidWithBestFriendName
  }
}
fragment DroidWithBestFriendNameAndForceSide on droid {
  best_friend {
   name
  }
  best_friend {
    forceSide {
      name
    }
  }
}
fragment DroidWithBestFriendName on droid {
  best_friend {
    name
  }
}
```

**Comment by hlship** [comment]
Haven't forgotten about this, still thinking about a way to do this without disrupting performance.  Basically, we've built Lacinia with the intent that it executes top to bottom, then builds bottom to top ... to address this situation, we have to figure if/when to do a deep merge after building.

**Comment by lennartbuit** [comment]
I stumbled over this issue today. I found that the reference implementation (graphql-js) does merge these selections:

- https://codesandbox.io/s/eager-moser-u3u9o?file=/src/index.js

And the spec has this example, that is eerily similar, but I can't quite figure out what it suggest implementors to do with that query:

- https://spec.graphql.org/June2018/#example-fdbb7

**Comment by hlship** [comment]
Believe it or not, I'm finally working on this, and have a pretty sweet solution ... I think!
