### ISSUE TITLE
Need a way to document the values of an enum.

### ISSUE THREAD

**Issue by hlship** [walmartlabs/lacinia#125]
I think this could go two ways.

Either way, the current behavior (:values is a seq of raw values) will be supported.

#1:  :values can also be a seq of maps with keys :value and :description.

#2: A :value-descriptions map of enum value to description string.

**Comment by bjonica** [comment]
I think the first way is the most idiomatic, as it lines up with how enum values are modeled [in graphql-js](http://graphql.org/graphql-js/type/#graphqlenumtype) as well as other types in lacinia.

Another reason I lean toward the first way is that it would be harder to maintain documentation when the value definitions are split from their descriptions. One could remove a value definition and forget to remove the definition. Would lacinia then check for unmatched value-descriptions and fail to compile the schema? The second option seems more complex.

**Comment by hlship** [comment]
Looking like it will look like:

```
{:enums
 {:status {:values [{:enum-value "OK" :description "No errors."}
                              {:enum-value "BAD" :description "Some errors."}]}}}
```
