### ISSUE TITLE
Enum is not enforced in an object field

### ISSUE THREAD

**Issue by itaied246** [walmartlabs/lacinia#140]
Maybe I didn't understand it correctly, or the `enum` is not working as expected.

I have this `enum` type:

```edn
{:platform
 {:description "Supported gaming platforms"
  :values      [:PLAYSTATION_4 :PLAYSTATION_3 :XBOX_ONE :XBOX_360 :PC]}}
```

And this `object`:

```edn
 :game
 {:fields
  {:name     {:type String}
   :platform {:type :platform}}}
```

As I understand `enum`s, only the values specified are allowed.
But if I return the following result:

```clj
:query/post-by-id (fn [context args value]
                       {:game {:name     "Tekken 7"
                                    :platform "my-platform"}})
```

It actually works and doesn't throw an error (as opposed to returning `String` for `Int` type).

Is it the correct behavior?

**Comment by hlship** [comment]
It is true, we don't validate the data provided by the field resolver functions.  The question is whether we should and, if the value provided isn't a match, is that a soft error or a thrown exception?

**Comment by itaied246** [comment]
Isn't that covered in graphql specs?
In `graphql-js` they return an error in the result.
Whatever you choose to implement, I think it is crucial to verify the enum, otherwise you open a door to broken API (think of database enums for example, no column can hold data other than the specified values).
