### ISSUE TITLE
Allow namespaced enums

### ISSUE THREAD

**Issue by tomasd** [walmartlabs/lacinia#146]
Currently enums are parsed as keywords. Would it be possible to allow also namespaced enums? 

I know that it's a problem with graphql specification as it does not allow "/" in enum names. But if there would be similar functions as in scalars (parse/serialize), that way we can customize namespace for enums.

Internal code can work with namespaced keywords and external code to graphql will see only the keyword name.

**Comment by hlship** [comment]
I wonder if this could be addressed as a custom type that happens to be a keyword.  I guess you would lose out on introspection of the possible values then.

I don't see us deliberately introducing features that break the spec.

A discussion on the Slack channel might be useful in terms of identifying the underlying issue and finding a good solution.
