### ISSUE TITLE
Dealing with namespaced keywords

### ISSUE THREAD

**Issue by borkdude** [walmartlabs/lacinia#15]
I'm trying to retrofit an existing REST endpoint (which returned EDN) to GraphQL using Lacinia.
The response contains a lot of namespaced keywords. Has Lacinia support for querying these?

**Comment by hlship** [comment]
Namespaces are a problem because the slash character is not allowed in a name (http://facebook.github.io/graphql/#sec-Names).

**Comment by bcarrell** [comment]
This is doable, but like @hlship mentioned, you'll need to find a way to map these keys in your data structure to keys in your GraphQL schema.  My suggestion would be to override the [default-field-resolver](https://github.com/walmartlabs/lacinia/blob/master/src/com/walmartlabs/lacinia/schema.clj#L806) (see the default one [here](https://github.com/walmartlabs/lacinia/blob/master/src/com/walmartlabs/lacinia/schema.clj#L798)) to instead look up using whatever namespacing you're using.

Does that help?

**Comment by borkdude** [comment]
@bcarrell That's exactly what I've been doing as a workaround, the double underscores. Looks like it's more difficult to retrofit GraphQL on our backend, as we are using URIs as keys as well. I'll close this for now.
