### ISSUE TITLE
Malformed subscription leads to 100% CPU consumption

### ISSUE THREAD

**Issue by yatagan** [walmartlabs/lacinia#150]
Looks like validation of subscriptions arguments is not perfect :)

**Comment by annapawlicka** [comment]
Could you provide more information, an example perhaps?

**Comment by yatagan** [comment]
Yes, I'll extract an example from my project.

**Comment by yatagan** [comment]
@annapawlicka I've made an example based on the `clojure-game-geek`
please check this commit: https://github.com/yatagan/clojure-game-geek/commit/8ebb291488fde51928f7de7b672592ca5511bf52

Steps to reproduce:

```
$ git clone https://github.com/yatagan/clojure-game-geek.git
$ cd clojure-game-geek
$ lein repl
user=> (start)
```
Run subscriptions in graphiql:

## Good case

```
subscription ($user_id: ID!) {
  compute(user_id: $user_id) {
    id
    member_name
  }
}
```

variables:
```
{
  "user_id": "dummy"
}
```

It works fine, returns dummy result.

## Bad case

```
subscription ($user_id: ID) {
  compute(user_id: $user_id) {
    id
    member_name
  }
}
```

variables:
```
{
  "user_id": "dummy"
}
```

It's the same query, but with malformed arguments (without the exclamation mark).

Check your CPU :(

**Comment by hlship** [comment]
I'm closing this, I believe it is fixed as part of https://github.com/walmartlabs/lacinia-pedestal/pull/46.
