### ISSUE TITLE
Port to CLJC possible?

### ISSUE THREAD

**Issue by wnr** [walmartlabs/lacinia#154]
Hi,

Would it be possible to rewrite this library to Clojure Common, so that it may be used client-side in clojurescript? 

I think running a GraphQL interface client-side would have many use cases. For instance, my team is developing a large bank application and we would really like to use GraphQL. However, deploying anything server-side is out of the question so we would like to ship an implementation within the app. Another use case would be prototyping apps, where you simply don't want the extra system overhead of deploying server applications just to serve your app with a GraphQL interface.

EDIT: Forgot to mention that I'm willing to give this a try if you think it is feasible.

**Comment by hlship** [comment]
I would like this at some point, very little of Lacinia could not be ported to ClojureScript, except the query and schema parser, which is built on Antlr4J.

It would be nice to introduce an intermediate form of the parsed query that could be agnostic about its source (it's very tied to how Antlr4J right now); this could also smooth out some issues related to certain tokens that can also be allowed as field names.

Every request goes through a parse stage, affecting parsing performance is therefore something that needs to be monitored carefully.

**Comment by hlship** [comment]
This is something I've thought about before, but not something that aligns with our (Walmart's) current priorities, so it's hard to justify working on it versus other things that need doing, including the tutorial.

**Comment by wnr** [comment]
Okay, thank you for your response. It sounds like someone in the core team should do such transition, so I'll leave it to the future in case you get a bit more time :)

I'll perhaps experiment with a CLJC GraphQL implementation on my own, as performance is not prioritised for us at this stage (we primarily want evaluate the tech).
