### ISSUE TITLE
Testing against stubbed schema

### ISSUE THREAD

**Issue by itaied246** [walmartlabs/lacinia#160]
I want to test my schema without the resolvers.
For instance, testing and making sure that:

- Non null values should return error when supplied null
- Enums
- Types
- Etc...

How can I verify and test against a schema without resolvers?

In `graphqljs` there is [validate](https://github.com/graphql/graphql-js/tree/master/src/validation) function,
which enable exactly that.

The only way I could think of is making a dummy `resolver-map`, that returns an empty function for each key.
But that would require me to write all of the resolvers twice,
and when combining with `component` it becomes a bit messy...

Any clean solution?

**Comment by hlship** [comment]
I don't follow what you are testing here?  Schema correctness?

**Comment by itaied246** [comment]
Yes, at the unit test level.

**Comment by timgilbert** [comment]
I would probably use this if it was available, as I'm working on code which generates schemas automatically. It's not a huge priority for me though; what I tend to do instead is set up dummy resolvers in test code.

**Comment by hlship** [comment]
I'm going to close this; I don't see this as core functionality needed by Lacinia.  I suspect you could write a filter that could walk the EDN and provided resolver functions before schema/compile is invoked.  I don't know that Lacinia can do a good, dependable, general case version of what you are looking for.

Generally, if I define an argument or field as `non-null`, I don't feel the need to write a test that Lacinia performs those checks.  I've written those tests once as part of the Lacinia tests themselves. 

Other errors, such as typos on type names, are caught at schema compile time.
