### ISSUE TITLE
Fields with arguments are not checked against fields in interface

### ISSUE THREAD

**Issue by hlship** [walmartlabs/lacinia#17]
We have good checks in place that a field in an object uses the same, or compatible, types as the field in an interface from which the object inherits.

However, there is no check that the interface field and the object field have the same arguments.

The interface and field should define the same set of arguments, with identical types (because argument types are limited, there's no question of unions, interfaces, or objects: just scalar types, enums, and input objects.

**Comment by annapawlicka** [comment]
Looking into it.

**Comment by annapawlicka** [comment]
Fixed in #106
