### ISSUE TITLE
::container-type-name is nil in top-level query resolver

### ISSUE THREAD

**Issue by timgilbert** [walmartlabs/lacinia#170]
The [docs here](http://lacinia.readthedocs.io/en/latest/resolve/type-tags.html#using-tag-with-type) say I should be using `(:com.walmartlabs.lacinia/container-type-name context)` to get the type I'm supposed to be returning from a resolver.

This works for field resolvers, but the value always seems to be nil when I call it from a top-level query resolver. My specific case resembles this (sorry, pseudocode but I can come up with a working minimal test-case if needed):

```clojure
 :queries
 {:check
  {:type    :MyType
   :resolve [:test/resolver :blah]}
```

...and then a resolver looking like:

```clojure
(defn my-resolver
  [unique-attribute]
  (fn [context args value]
    (log/spy (:com.walmartlabs.lacinia/container-type-name context))
    {:my "thing"})))
```

...and I'm always seeing `nil` as the container-type-name value.

Is there a reason this value isn't set for top-level resolvers, and if so is there another way to determine the type I'm supposed to be returning from inside of the resolver?

**Comment by hlship** [comment]
This is a documentation bug.  I'll fix that, I can see how you were confused.  The ::lacinia/container-type-name is the type of the value passed *into* the resolver, not the type of value returned by the resolver.

**Comment by hlship** [comment]
I've updated the documentation.  Should be live shortly.

**Comment by timgilbert** [comment]
Great, thanks. Is there a way to get the type that is meant to be returned from the resolver? (I'm messing around with dynamic schema generation and it would be convenient to have a way to get access to it from inside the resolver without having to reference the schema itself.)

**Comment by hlship** [comment]
I'm afraid there isn't currently. It's kind of assumed that you know that when you are assembling the schema and resolvers. We can discuss in the Clojurian's slack.
