### ISSUE TITLE
How to serve with HTTP?

### ISSUE THREAD

**Issue by salmazov** [walmartlabs/lacinia#174]
Hello!

I found only REPL examples in tutorial in the Lacinia docs. But how to make requests via HTTP to Ring/Compojure with Lacinia?

**Comment by kgann** [comment]
Recommendations are in `README.md`.

> This library can be plugged into any Clojure HTTP pipeline. The companion library lacinia-pedestal provides full HTTP support, including GraphQL subscriptions, for Pedestal.
