### ISSUE TITLE
Type system is insufficient - list and not-null can not be freely combined

### ISSUE THREAD

**Issue by hlship** [walmartlabs/lacinia#18]
The current system is quite limited: you can add a not-null qualifier, meaning that the value may not be nil.  You can add a list qualifier, meaning that the resolver returns a seq of values, not a single one.  You can combine the two, meaning that the the values may not be nil (though the list itself may be).

This is a subset of what the GraphQL spec calls for; we should be able to say that a field's type is a non-null list of lists of non-null Strings, for example.

That means the `list` and `not-null` qualifiers need to be fully nestable, with some system of reified types to make it all work; a somewhat fundamental change to how the executor operates.

**Comment by mpenet** [comment]
:+1:  

I am actually in need of `(list (list Int))` to port our schemas to graphql, I am not sure how to model this in the meantime. If you have work arounds feel free to advise me.

**Comment by bcarrell** [comment]
Right.  This is something that we've known was an issue for a while but we
don't have that issue with our services.  Let's prioritize this to be fixed
asap.

**Comment by kgann** [comment]
@mpenet 

If you're willing to change your schema, I _think_ you could use wrapper objects as a workaround. I haven't tested this.

```clojure
:input-objects
{:inputInts {:fields {:ints {:type (list Int)}}}}

:objects
{:ints {:fields {:ints {:type (list Int)}}}}

:queries
{:foo {:args {:ints {:type (list :inputInts)}}}
       :type (list :ints)
       :resolve :foo-resolver}
```

Arguments and resolved types may be a bit odd:

```javascript
{
  foo(ints: [{ints: [1 2 3]}, {ints: [4 5 6]}]) {
    ints
  }
}
```

```clojure
{:data {:foo [{:ints [1 2 3]}
              {:ints [4 5 6]}]}
```
