### ISSUE TITLE
Initial board game schema in tutorial missing `non-null` for ID

### ISSUE THREAD

**Issue by xiongtx** [walmartlabs/lacinia#180]
The [initial schema](http://lacinia.readthedocs.io/en/latest/tutorial/init-schema.html#id2) has `BoardGame` ID like:

```clojure
{:BoardGame
  {:description "A physical or virtual board game."
   :fields
   {:id {:type ID}
   ...}}}
```

whereas it should be 

```clojure
{:id {:type (non-null ID)}
   ...}
```

The `non-null` magically appears in a [later version of the schema](http://lacinia.readthedocs.io/en/latest/tutorial/designer-data.html#id3) ✨.

I don't see a `resources/cgg-schema.edn` anywhere in Lacinia itself; otherwise this is a trivial fix.

**Comment by hlship** [comment]
Fixed.
