### ISSUE TITLE
snapshots / nightlies 

### ISSUE THREAD

**Issue by devth** [walmartlabs/lacinia#182]
Any plans to release snapshots from CI? I'm itching to benefit from https://github.com/walmartlabs/lacinia/pull/179 but it's not released yet.

**Comment by hlship** [comment]
We try to keep to a monthly release cadence.

I'd rather not have to get into the '-SNAPSHOT' naming cycle.  I just update the version number sometime after a release and the next.

Building locally takes `git clone` + 20 seconds.
