### ISSUE TITLE
Generate GraphQL SDL

### ISSUE THREAD

**Issue by devth** [walmartlabs/lacinia#183]
Related to https://github.com/walmartlabs/lacinia/pull/113 except more like the opposite. Could lacinia generate a `.graphql` schema? I'm specifying my schema in edn currently, but need a proper `.graphql` schema for consuming graphql from a client (which happens to be written in Relay + TypeScript).

**Comment by hlship** [comment]
This could be done, somewhat easily from the input (not compiled) schema. Alternately, you could use introspection to build up the schema.

I would consider accepting a PR for this, but we don't currently have the bandwidth to add such a feature.

**Comment by luchiniatwork** [comment]
Has anyone done this or is it still up for grabs?

**Comment by hlship** [comment]
Up for grabs.  At this point, might be possible to build from the compiled schema, with a few more selection functions and some helpers.
