### ISSUE TITLE
Get ID from parent

### ISSUE THREAD

**Issue by lxsli** [walmartlabs/lacinia#184]
Is it legit to access `:com.walmartlabs.lacinia/selection` from the application context in a resolver? And if not, how should I be doing this please?

Suppose I have a schema like:

```graphql
type Page {
    id: Int!
    next: Page
    prev: Page
}

type Query {
    Page(id: Int!): Page
}
```

When I'm resolving a sub-page, I need to know whether my id is from 'next' or 'prev'. Page has two fields of type Page, so I can't just check the parent type to know which field refers to 'me' while I'm resolving a sub-page.

I can attach a resolver like:

```clojure
(defrecord Page [id next prev])

(defn r-page [ctx {:keys [id]} parent]
    (let [id (some id (get parent (get-field-from-ctx ctx)))]
        (map->Page {:id id
                    :next (inc id)
                    :prev (dec id)})))

(defn get-field-from-ctx [ctx]
    (-> ctx :com.walmartlabs.lacinia/selection :field))
```

This should answer a query like:

    {
        Page(id: 1) {
            next {
                id
            }
        }
    }

with:

    {
        Page {
            next {
                id: 2
            }
        }
    }

**Comment by hlship** [comment]
I'm having trouble figuring out what you want.

From what I can tell, in your case, I would attach a `next` and `prev` resolver to the `next` and `prev` fields of `Page`.  The resolvers would get the `:id` from the parent then access `(inc id)` or (dec id)` from whatever your backend is.
