### ISSUE TITLE
Schema Stitching

### ISSUE THREAD

**Issue by loganpowell** [walmartlabs/lacinia#185]
So happy to see this project! Just curious to know if you guys support (or plan to) [Schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html). I couldn't find anything by searching the repo.

**Comment by hlship** [comment]
No current plans for this, it's still a somewhat early proposal for GraphQL in general.

**Comment by loganpowell** [comment]
I hastily created this issue without first wrapping my head around the current .clj/c/s ecosystem covering graphql. I realize now that `lacinia` is more of a full-fledged `graphql-express`-like replacement for Clojure than a [graphql-tools](https://github.com/apollographql/graphql-tools) library, which is where stitching is taking place in the .js world. I apologize and will close the issue.

Btw, did you hear about the [latest release of graphql-tools](https://dev-blog.apollodata.com/the-next-generation-of-schema-stitching-2716b3b259c0)? looks like they're maturing!
