### ISSUE TITLE
Variables fails for object arguments

### ISSUE THREAD

**Issue by thenikso** [walmartlabs/lacinia#189]
I receive an error similar to #164 when attempting this (valid) query:

```graphql
query test($a_string: String) {
  something(objParam: { objField: $a_string }) {
    id
  }
}

{ "a_string": "something" }
```

The returned error is:

```
Exception applying arguments to field `something': For argument `objParam', no method in multimethod 'process-dynamic-argument' for dispatch value: :object
```

Having the argument represent the entire object works, yet the exemplified query should work as well. A similar error happens with :array (ie: `objParam: [{ objField: $a_string }]`).

**Comment by hlship** [comment]
This should work, if you could provide a schema to go with it, it would help with testing and isolating what's going on.

**Comment by hlship** [comment]
I'm seeing this problem as well. I'll be looking into it shortly. It gets complicated to implement, but I'll see what I can do.

**Comment by hlship** [comment]
Are we sure this should work as per the spec or RI?

**Comment by hlship** [comment]
Oh, this is a tough one, but I'll beat it.

**Comment by mikewin** [comment]
:array still not allow  variable
for example:
query($t:Float){order_by_props(limit:10,filter:{eq:[{field_name:"havePay"},{float_val:$t}]}){
havePay,subMonthCount,orderStatus,subMonth,createAt,subCount,subYear,id,magazine{id},customer{openid}}}

result:
{
  "errors": [
    {
      "message": "Exception applying arguments to field `order_by_props': For argument `filter', for argument `eq', no method in multimethod 'process-dynamic-argument' for dispatch value: :array",
      "locations": [
        {
          "line": 1,
          "column": 17
        }
      ],
      "extensions": {
        "field": "order_by_props",
        "argument": "eq"
      }
    }
  ]
}
