### ISSUE TITLE
Async Processing - Design Overview

### ISSUE THREAD

**Issue by hlship** [walmartlabs/lacinia#19]
Added here to collect comments.

We already have the `resolve-as` function, and the related `ResolverResult`.
These are special values that can be returned by a resolver function (in 0.13.0); they are used to allow a return value (or seq of values) along with an error map (or seq of error maps).

Asynchronous field resolvers would return a kind of deferred ResolverResult, and would later (in a different thread) provide the resolved value and/or error map(s).

My proposal is to extend the `ResolverResult` protocol to support asynchronous behavior.

A new function, `when-ready!`, will be added; its argument is a data callback function invoked when the resolved value and error are available.
The data callback is passed the the tuple's value and errors, and the return value from the callback is ignored.
`when-ready!` is stateful: it may only be invoked once.

For `ResolverResultImpl`, `when-ready!` can immediately invoke the callback.

A new protocol, `DeferredResolverResult`, and method, `resolve-async!`, will be introduced. `resolve-async!` is the method equivalent to `resolve-to` as applied for deferred ResolverResult instances.
Invoking this method provides the value and/or error, and invokes the data callback.
This method is stateful and may only be invoked once.
A new function, `resolve-deferred`, returns an instance that implements `ResolverResult` and `Deferred`.

For the `ResolverResult` implementation,  the data callback will typically not be invoked immediately, instead it will be invoked from a thread, started from the resolver function, invokes the `resolve-async!` method.

The `resolved-value` and `resolved-errors` methods on a `DeferredResolverResult` will block until data is available (via `resolve-async!`).

So, basically, there's going to be a whole lot of `when-ready!` callbacks that accept a resolved value (and/or errors) and turn around, process or combine those values, and then `resolve-async!` on a different instance.
I can definitely see some additional functions or macros to make that easier.

What I haven't quite puzzled out yet is timeouts; do we set just a global timeout?  Do we just substitute nils in when there's a timeout, or fabricate a timeout error map?  Do you specify timeouts with every `when-ready!`? Maybe an optional alternate callback for when a timeout occurs.

Or as Matt has opined: timeouts are managed by the resolver function, so do them right.

Maybe there's a default timeout time and timeout value and error, and this is in effect globally, but there's an `on-timeout!` method as well that lets it be overridden on an individual tuple?

Basically, you probably want a more generous timeout on the top level, and then smaller timeouts at the leaves, where field resolvers actually get invoked.

Suggestions on better names for protocols and methods are welcome.

I've also thought about a callback, provided as an option to c.w.l.schema/compile, that would be used to decorate resolver functions to adapt their return value, i.e., convert a core.async channel into a DeferredResolverResult.

**Comment by candid82** [comment]
@hlship I think it'd be helpful to have an example of a resolver for async scenario. Did you consider embracing core.async instead of creating customer API for async resolvers? Would it be possible to allow resolvers return a channel that conveys regular resolver result (`ResolvedTuple` or anything else)? This would be similar to how pedestal handles async.

**Comment by hlship** [comment]
```
(defn gizmo-resolver
    [context args value]
    (let [tuple (resolve-deferred)]
      (do-in-a-new-thread
        (->> value read-gizmo (resolve-async! tuple)))
      tuple))
```

**Comment by mpenet** [comment]
It also seems to me it's something that could be solved using
core.async promise-chan, it's essentially the "deferred" you describe
and since a lot of async stuff in clojure is interfaced with
core.async this would play nicely with them, and allow to plug timeouts and whatnot at the resolver level super easily with alts!

```clj
(defn gizmo-resolver
    [context args value]
    (let [prom (async/promise-chan)]
      (do-in-a-new-thread
        (->> value read-gizmo (async/put! prom)))
      prom)) 
```

**Comment by hlship** [comment]
Normally I love core.async, but I'm also looking to avoid any further dependencies, and core.async is a big one.

**Comment by stijnopheide** [comment]
What about [manifold](https://github.com/ztellman/manifold)? It's a beautiful API to work with and allows you to define a custom executor.

**Comment by am0ry** [comment]
It's better to let users decide what async library they'd like to use. Callbacks are easily integrated with core.async (and Manifold).

**Comment by am0ry** [comment]
I like @mpenet's suggestions. Setting timeouts and handling async execution seems outside the bounds of Lacinia. 

Also, Clojure has a built-in "deferred" object api: https://clojuredocs.org/clojure.core/promise. Although I can see why it would be useful to define a new protocol.

**Comment by hlship** [comment]
Promise is good to a point, but there isn't an option other than blocking with a timeout and polling with `realized?`. The point of the the `when-ready!` and `resolve-async!` is to provide a third option, where code gets executed when data is available. It's brain dead simple compared to core.async, BUT it's solving a simpler problem: a single "publisher" and single "subscriber".

**Comment by hlship** [comment]
Made a few updates; what I long ago called `ResolvedTuple` was renamed to `ResolverResult` before 0.13.0.
