### ISSUE TITLE
Idea: Add an ability to merge maps in schema EDN. 

### ISSUE THREAD

**Issue by annapawlicka** [walmartlabs/lacinia#195]
It would be helpful to be able to merge maps on the schema file level. Even when we use `interfaces`, we have to list all fields in every object that implements the interface which results in a lot of copying and pasting of the same fields in the schema file. It would be nice if we could say
```
;; fields that can be reused in object definitions
;; :common is only used to compile schema and is later removed
:common 
{:Foo
 {:fields {:a {:type String}}}}

:objects
{:Bar
 {:extends Foo
  :fields {:b {:type Int}}}
 :Baz
 {:extends Foo
  :fields {:c {:type Long}}}
```
that would result in
```
:objects
{:Bar
 {:fields {:b {:type Int}
           :a {:type String}}
 :Baz
 {:fields {:b {:type Int}
           :c {:type Long}}}
```
Basically, something to reduce the copying and pasting in the EDN file. Perhaps `extends` is too similar to `implements` in `interfaces` and therefore confusing, so maybe `merge-in` could be used instead.

**Comment by hlship** [comment]
Maybe feed the schema to schematic before processing :-)

Earlier versions of the code would inherit interface details, including resolvers, into implementing objects, but that caused some problems.

This could be implemented as a step between `edn/read-string` and `schema/compile`.

**Comment by hlship** [comment]
This may be worthwhile is some applications of lacinia, but does not appear to be necessary as a core feature.
