### ISSUE TITLE
hitting race condition in resolve-promise

### ISSUE THREAD

**Issue by henryw374** [walmartlabs/lacinia#200]
Hi,

I see there's a note in _com.walmartlabs.lacinia.resolve/resolve-promise_  about race conditions and indeed I am seeing that problem. 

FYI I've tried creating a _ReentrantLock_  and doing lock/unlock calls at the start/end of the bodies of the two ResolverResult methods in resolve-promise.  That appears to work ok. Just doing `(locking this ...)` around the bodies resulted in deadlock in some cases.

Cheers,
Henry

**Comment by hlship** [comment]
This should be fixed by #197
