### ISSUE TITLE
Failure to compile under clojure 1.8 with future.spec dependency included

### ISSUE THREAD

**Issue by 13tales** [walmartlabs/lacinia#206]
Hi there. I'm a relative clojure novice attempting to follow the lacinia tutorial and get a minimal graphql server running. I'm using clojure 1.8.
Having defined the schema as per http://lacinia.readthedocs.io/en/latest/tutorial/init-schema.html, when attempting to run the project I get the following error:

`Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: simple-keyword? in this context, compiling:(com/walmartlabs/lacinia/internal_utils.clj:255:19)`

I've added a project dependency for `clojure-future-spec` as per the docs. Have I done something wrong, or is the current documentation out of date?

Thanks!

**Comment by hlship** [comment]
Well then, that's something we should have tested. Sorry.
