### ISSUE TITLE
Accept clojure sets as valid graphql list type when returned from resolver

### ISSUE THREAD

**Issue by mpenet** [walmartlabs/lacinia#21]
Right now it returns sets as strings. 
This is something quite common in clojure apis and would be more friendly than having to walk our return data to convert sets to list/vec or define a custom scalar that reads the string (lots of wasted cycles for something like this, set->string->set). Worth noting that's something all (?) json marshaling libraries for clojure do transparently too.

it seems mostly due to` sequential?` checks instead of `(or (sequential? x) (set? x))`, ex here https://github.com/walmartlabs/lacinia/blob/61bcaa20cacc66ebbb20b8adf07949fd45d124ef/src/com/walmartlabs/lacinia/schema.clj#L296-L308

**Comment by bcarrell** [comment]
Seems fine to me, feel free to send a PR or we'll work on fixing this soon!

**Comment by mpenet** [comment]
No longer relevant since #23 was merged
