### ISSUE TITLE
Allow application to transform enum values between GraphQL values an application-specified values

### ISSUE THREAD

**Issue by solussd** [walmartlabs/lacinia#221]
It would be nice to have enum resolvers, or maybe enum transformations (e.g., parser/serializer) to allow for internal representations of enum values as namespaced keywords. For example, if I had an enum type `Role` with possible values `ADMIN`, `MEMBER`, and `GUEST` that I want to represent internally as `:role/admin`, `:role/member`, and `:role/guest` I could have a transformer that manages that transformation.

Currently I have to perform the mapping manually or heuristically.

There is some prior art in Apollo: https://www.apollographql.com/docs/graphql-tools/scalars.html#internal-values

I'll add: I'm happy to open a PR for this if it makes sense.

**Comment by hlship** [comment]
This is a good idea, but I'm not sure when I'll have a chance to implement it.

**Comment by Lokeh** [comment]
I would really appreciate this. It feels very idiomatic and might allow easier integration with other Clojure-y things like clojure.spec!

**Comment by miikka** [comment]
This could be very handy for us: we're trying to upgrade from an old version Lacinia that did not enforce enum values and now our GraphQL schema is full of lies. This feature would allow us to handle broken enum values more gracefully.

**Comment by hlship** [comment]
Working on this now; essentially adds :parse and :serialize as optional keys to Enums.  The default is identity and as-keyword.

Parsing:

The string from parsed from the query document (or string variable) is converted to a keyword, validated as a known Enum value, then passed through the :parse fn (default is identity) to create the application value (i.e., the value that may be provided as a field argument).

Serializing:

The resolver function returns an arbitrary value, this is passed through the serializer (the default serializer leaves keywords alone, and converts strings and symbols to unqualified keywords), then that result is verified to be defined by the Enum and becomes the selected value that ultimately goes in the response.
