### ISSUE TITLE
Change enum values to be keywords, not strings

### ISSUE THREAD

**Issue by hlship** [walmartlabs/lacinia#26]
As of current, 0.14.0, enums are treated as a special string.  However, enums must be names, which represent a subset of what's allowed in a Clojure keyword. In general, enums are backed by keyword values in the raw data ... why not just allow enums to be keywords that serialize to strings?  I think this would make server-side coding with enums more straightforward.

**Comment by bcarrell** [comment]
Seems fine to me.
