### ISSUE TITLE
selections-tree returns incomplete result when aliases are used

### ISSUE THREAD

**Issue by oliyh** [walmartlabs/lacinia#262]
Hi,

We are using `selections-tree` to look ahead at a query but I found that when the same subfield is selected more than once (with aliases) the last one wins. Here's an example:

```graphql
query { 
  foo {
    a: bar(baz: true)
    b: bar(baz: false)
  }
}
```

I would expect `selections-tree` to return two selections for `bar`, one with the arg `baz: true` and one with the arg `baz: false` but because it is a map the second `baz` overwrites the first and the result, running `selections-tree` on the context in the resolver for `foo` is:

```clojure
{:foo/bar {:args {:baz false}}}
```

To be complete the output should be something like this:

```clojure
[{:field-name :foo/bar
  :attributes {:baz true}}
 {:field-name :foo/bar
  :attributes {:baz false}}]
```

Obviously this is a new return type and I had to invent the name `attributes` so I haven't written a PR as this requires decisions best left to you.

Thanks for your continued work on Lacinia!

**Comment by hlship** [comment]
That is an unfortunate oversight on our/my part!

**Comment by hlship** [comment]
What about a :field-name of `:QueryRoot/bar` rather than just `:bar`, I think that would be more useful.

I'm looking at doing a pass through the error messages to make them less verbose but use the `:<Object>/<field>[.argument]` syntax, consistent with the keys used with external markdown documentation.

**Comment by oliyh** [comment]
They are actually already like that, in my example they would be `:foo/bar`.
