### ISSUE TITLE
Explicit null arguments skip scalar parse functions

### ISSUE THREAD

**Issue by sashton** [walmartlabs/lacinia#276]
If a parameter's type is `Int`, and an explicit `null` value is provided for that field in the query, the scalar's parse function will not get executed, and code in the resolver which is expecting and `Integer` type will throw a runtime exception.

I would expect that the same behavior happens for other scalars as well, `Int` is used as an example.

**Comment by hlship** [comment]
nil should stay nil BUT
- if the argument is required, it should be an execution error
- if the argument has a default value, the default value should *not* be used
The default value should only be used if the argument is omitted entirely, not passed as nil

From the spec:

> Arguments can be required. An argument is required if the argument type is non‐null and does not have a default value. Otherwise, the argument is optional.

**Comment by sashton** [comment]
Yes, based the spec I agree, nil stays nil.
