### ISSUE TITLE
A non-null field should be optional-able by providing a default-value

### ISSUE THREAD

**Issue by sashton** [walmartlabs/lacinia#278]
From the spec: 
>Arguments can be either required or optional. When an argument is optional, we can define a default value

A non-null argument should still be able to be optional, by using default-values.

Example test:
```
(deftest default-value-is-used-for-non-null-argument-when-not-provided
  (let [schema (schema/compile {:queries
                                {:echo
                                 {:type :String
                                  :args {:input {:type '(non-null String)
                                                 :default-value "Default"}}
                                  :resolve (fn [_ args _]
                                             (str "Echo: " (:input args)))}}})]
    (is (= {:data {:echo "Echo: whatever"}}
           (execute schema "{ echo(input: \"whatever\") }")))

    (is (= {:data {:echo "Echo: Default"}}
           (execute schema "{ echo }")))))
```

**Comment by hlship** [comment]
My read of that spec line is that "A default value may be defined for optional arguments, but not for required."  So a non-null argument can't have a default.  But it's slightly ambiguous.  Let me peek in the latest spec, rather than the June 2018.

**Comment by hlship** [comment]
> Inputs (such as field arguments), are always optional by default. However a non‐null input type is required. In addition to not accepting the value null, it also does not accept omission. For the sake of simplicity nullable types are always optional and non‐null types are always required.

**Comment by sashton** [comment]
From https://github.com/graphql/graphql-spec/pull/418
>NEW: Non-null arguments and input object fields are no longer required to be provided a value/variable if that argument also supplies a default value.
NEW: Similarly, non-null input object fields can be omitted if they supply a default value. (Note that previously this validation clause was missing from the spec, however has long been included in reference implementations)
NEW: All variables can now have default values by way of removing a validation rule. Previously it was invalid to supply a default value with a non-null variable.

https://github.com/graphql/graphql-spec/pull/418/files#diff-961bce39801a71b97bd810a2b7b6c535R731

**Comment by sashton** [comment]
Also from https://github.com/graphql/graphql-spec/blob/master/spec/Section%205%20--%20Validation.md#argument-uniqueness
>Arguments can be required. An argument is required if the argument type is non-null and does not have a default value. Otherwise, the argument is optional.

If is field is non-null, but also has a default value, then it is not a required field.

**Comment by hlship** [comment]
Ok then.

I might as well update the other PR before it gets merged.

**Comment by hlship** [comment]
I think there's code & test for non-null arguments may not have default values; that can go!
