### ISSUE TITLE
Queries without Content-Type header result in "IOException: UT000034: Stream is closed"

### ISSUE THREAD

**Issue by duncan-bayne** [walmartlabs/lacinia#279]
I'm using lacinia 0.32.0 through [Luminus](https://github.com/luminus-framework/luminus), and have noticed that making a query without passing the Content-Type header causes lacinia to raise an unhandled exception.

E.g.:

```
$ curl 'http://localhost:3000/api/graphql' -X POST --data '{ hero { name } }'
{"type":"exception","class":"java.io.IOException"}%                                                                                                                       

$ curl 'http://localhost:3000/api/graphql' -X POST --data '{ hero { name } }' -H 'Content-Type: application/graphql'
{"data":{"hero":{"name":"Luke"}}}%  
```

I don't know whether this is a bug, exactly - I'm not sure it _should_ respond w/o an appropriate Content-Type.  But the unhandled exception seems odd.

**Comment by hlship** [comment]
This might be an issue with lacinia-pedestal; lacinia doesn't do anything on the HTTP layer, it's just a code-level API.  I'm not familiar with Luminus, so I can't say what's going on.
