### ISSUE TITLE
null collapsing issue

### ISSUE THREAD

**Issue by mpenet** [walmartlabs/lacinia#29]
As per discussion on slack, we sometimes get `com.walmartlabs.lacinia.executor/null` exposed in results that would be caused by faulty null collapsing.
```json 
{
  "data": {
    "users": [
      {
        "id": "com.walmartlabs.lacinia.executor/null"
      }
    ]
  },
  "errors": [
    {
      "message": "Non-nullable field was null.",
      "locations": [
        {
          "line": 2,
          "column": 53
        }
      ],
      "query-path": [
        "users",
        "id"
      ]
    }
  ]
}
```

**Comment by bcarrell** [comment]
Can you provide your schema?  I'm assuming you had this discussion with @hlship because I'm not on Slack.

**Comment by mpenet** [comment]
The schema is quite big, but that field is `:id {:type (non-null ID)}`

**Comment by Atsman** [comment]
It must not return data. JS implementation returns error "Cannot return null for not nullable field..."

**Comment by hlship** [comment]
Can you verify that this still occurs using more recent versions of Lacinia?  I strongly suspect this has been incidentally fixed at some point.

**Comment by hlship** [comment]
Please re-open with test cases against more recent Lacinia.  As noted above, I suspect this is incidentally fixed subsequent to the initial report.
