### ISSUE TITLE
Detect breaking changes made to the api and schema coverage checks

### ISSUE THREAD

**Issue by zyxmn-rvu** [walmartlabs/lacinia#296]
Is there a recommended route when using lacinia, to:
1)  detect breaking changes made to the api 
2)  check schema coverage

**Comment by hlship** [comment]
This is an idea that has bounced around internally, that we could provide two schemas and execute a function that would determine if the diff was backwards compatible.  Seems like something that could be implemented by a third-party library.

**Comment by hlship** [comment]
I think this is an excellent idea that could be fully implemented outside of Lacinia.  Glad to provide a pointer to an external project once implemented.
