### ISSUE TITLE
Int type parses/coerces as (32 bit) int, not (64 bit) long

### ISSUE THREAD

**Issue by hlship** [walmartlabs/lacinia#3]
Large numeric values, stored as type `long`, are conformed to ints:

```
(defn ^:private coerce-to-int
  [v]
  (cond
    (number? v) (.intValue v)
    (string? v) (Integer/parseInt v)
    :else (throw (ex-info (str "Invalid Int value: " v) {:value v}))))

(defn ^:private coerce-to-float
  [v]
  (cond
    (number? v) (double v)
    (string? v) (Double/parseDouble v)
    :else (throw (ex-info (str "Invalid Float value: " v) {:value v}))))

(def default-scalar-transformers
  {:String {:parse (conformer str)
            :serialize (conformer str)}
   :Float {:parse (conformer #(Double/parseDouble %))
           :serialize (conformer coerce-to-float)}
   :Int {:parse (conformer #(Integer/parseInt %))
         :serialize (conformer coerce-to-int)}
   :Boolean {:parse (conformer #(Boolean/parseBoolean %))
             :serialize (conformer #(Boolean/valueOf %))}
   :ID {:parse (conformer str)
        :serialize (conformer str)}})
```

This ends up truncating the values.

```
(.intValue 1461381425413)
=> 1092544773
```

**Comment by hlship** [comment]
This may not be a bug; the spec identifies the Int type to be explicitly 32 bits.

**Comment by bcarrell** [comment]
I don't view this as a bug.  I think the current behavior is correct.  From the spec:

> GraphQL servers should coerce non‐int raw values to Int when possible otherwise they must raise a field error.

These large numeric values are being handled correctly in my view.  They're not integers by definition and they're being coerced to truncated values.

Alternatively, we could raise field errors.

**Comment by candid82** [comment]
Truncated value is useless most of the time. I think raising an error in case of overflow would be a better approach...

**Comment by hlship** [comment]
I believe that as of 0.17.0, an out-of-range integer value will throw an exception on input/output.  I'll double check and close this issue if so.

**Comment by baldmountain** [comment]
As a workaround I have a scalar like:

```clojure
:scalars {
  :Long {
    :parse (schema/as-conformer #(Long/parseLong %))
    :serialize (schema/as-conformer #(do %))
  }
}
```

in our project's schema. Seems to handle long values properly.

**Comment by hlship** [comment]
I've had the thought that we could add a compiler option, `:extra-scalars`, to add a Long and perhaps a UUID scalar.

**Comment by hlship** [comment]
```
(def schema (schema/compile {:queries {:value {:type :Int :resolve (constantly Long/MAX_VALUE)}}}))
=> #'user/schema
(l/execute schema "{ value }" nil nil)
=>
{:data #ordered/map([:value nil]),
 :errors (#com.walmartlabs.lacinia.schema.CoercionFailure{:message "Int value outside of allowed 32 bit integer range.",
                                                          :value "9223372036854775807",
                                                          :locations [{:line 1, :column 0}],
                                                          :query-path [:value]})}
```

So it coerces to nil with an error, I think that's good enough.
