### ISSUE TITLE
UUID is not serialize

### ISSUE THREAD

**Issue by jeans11** [walmartlabs/lacinia#304]
Hi!

I'm using the version `0.35.0` and I have a mistake to serialize UUID. I have the following error message:

```clj
{:message "Unable to serialize #uuid \"8024eeea-179f-47c3-b5e7-0dffcfb9715e\" as type `ID'."}]}
```

Thanks

**Comment by hlship** [comment]
Which version were you using before the upgrade to 0.35.0.  Lacinia follows the GraphQL spec and AFAIK, IDs are only mapped to Strings or integers; but you can override the ID scalar to support UUIDs as well.

**Comment by jeans11** [comment]
Thanks for your help!
I used the `0.21.0` before the upgrade to `0.35.0`. How can I override the ID scalar?

**Comment by jeans11** [comment]
Ok got it https://lacinia.readthedocs.io/en/latest/custom-scalars.html

**Comment by Ayush1325** [comment]
How can I do custom scalars in an EDN file? Using the same method as given in the docs results in the following error:
```
{
  "errors": [
    {
      "message": "No dispatch macro for: ("
    }
  ]
}
```
Here is my edn file
```
{:scalars
 {:ID
  {:parse #(when (string? %)
             (try
               (java.util.UUID/fromString %)
               (catch Throwable _
                 %)))
   :serialize #(try
                 (str %)
                 (catch Throwable _
                   %))}}
 :objects
 {:agency
  {:fields {:id      {:type ID}
            :name    {:type String}
            :address {:type String}}}}
 :queries
 {:findAgencies {:type    (list :agency)
                 :args    {:name {:type String :default-value ""}}
                 :resolve :agency-find-name}}
 :mutations
 {:addAgency {:type :agency
              :args {:name {:type (non-null String)}
                     :address {:type String}}
              :resolve :agency-add}
  :updateAgency {:type :agency
                 :args {:id {:type (non-null ID)}
                        :name {:type (non-null String)}
                        :address {:type String}}
                 :resolve :agency-update}
  :deleteAgency {:type Boolean
                 :args {:id {:type (non-null ID)}}
                 :resolve :agency-delete}}}
```

**Comment by Ayush1325** [comment]
> How can I do custom scalars in an EDN file? Using the same method as given in the docs results in the following error:
> 
> ```
> {
>   "errors": [
>     {
>       "message": "No dispatch macro for: ("
>     }
>   ]
> }
> ```
> 
> Here is my edn file
> 
> ```
> {:scalars
>  {:ID
>   {:parse #(when (string? %)
>              (try
>                (java.util.UUID/fromString %)
>                (catch Throwable _
>                  %)))
>    :serialize #(try
>                  (str %)
>                  (catch Throwable _
>                    %))}}
>  :objects
>  {:agency
>   {:fields {:id      {:type ID}
>             :name    {:type String}
>             :address {:type String}}}}
>  :queries
>  {:findAgencies {:type    (list :agency)
>                  :args    {:name {:type String :default-value ""}}
>                  :resolve :agency-find-name}}
>  :mutations
>  {:addAgency {:type :agency
>               :args {:name {:type (non-null String)}
>                      :address {:type String}}
>               :resolve :agency-add}
>   :updateAgency {:type :agency
>                  :args {:id {:type (non-null ID)}
>                         :name {:type (non-null String)}
>                         :address {:type String}}
>                  :resolve :agency-update}
>   :deleteAgency {:type Boolean
>                  :args {:id {:type (non-null ID)}}
>                  :resolve :agency-delete}}}
> ```

My bad, found the answer

> Attaching Scalar Transformers
> 
> As with field resolvers, the pair of transformers for each scalar have no place in an EDN file as they are functions. Instead, the transformers can be attached after reading the schema from an EDN file, using the function com.walmartlabs.lacinia.util/attach-scalar-transformers.
