### ISSUE TITLE
Is it still in alpha stage?

### ISSUE THREAD

**Issue by ctjhoa** [walmartlabs/lacinia#305]
Hi,

from the README

> Although this library is used in production at Walmart, it is still considered alpha software - subject to change. We expect to stabilize it in the near future.

Since it has been written 3 years ago and that many people seems to use it in production, I would like an update on the status of this library. Is this statement still true? Do you have any roadmap/plan to release a stable version?

**Comment by hlship** [comment]
We've had some discussions about what it would take to get to a beta or GA state; basically some inspiration about what to do about directives in a meaningful way, along with a few little cleanups and depredations.
