### ISSUE TITLE
How do I return errors without the `data` field in responses?

### ISSUE THREAD

**Issue by kipz** [walmartlabs/lacinia#311]
According to the current spec, it's totally valid to return errors without a `data` field:

https://graphql.github.io/graphql-spec/draft/#sec-Errors

From what I can tell, there's no way to instruct lacinia to do this, and that the field is always returned:

https://github.com/walmartlabs/lacinia/blob/ea9468d2f9d64286fbf64486b65b8b3f62225cb7/src/com/walmartlabs/lacinia/executor.clj#L475

Clients might want to use the presence of the `data` field to determine error handling behaviour:

* data (null or otherwise) and errors: could be some usable data in the response
* no data and errors: something serious happened, such as network failure or whatever. No usable data in the response

I believe some modes of the apollo-client do this.

I was thinking that we could add `resolve/as-error` function (or similar) which would distinguish it from `resolve/with-error`.

**Comment by hlship** [comment]
We've painfully found that over-using errors is problematic. For example, we have clients in the field (e.g., mobile apps) that treat any errors as a total failure of the request (we actually edit out the errors for that client).

Essentially, if the query can be parsed and validated sufficiently to execute the query, then the `data` key, even if nil, must be present in the response.

In fact, the best use of `with-error` is early in a resolver, to validate that (for example) input arguments are valid.

We're gradually shifting to using `with-warning` (which is non-standard) to report processing errors that are recoverable, such as a failure accessing a 3rd party service.

**Comment by kipz** [comment]
Yeah, this whole area is a bit of a mess IMHO, but in the interest of interoperability, shouldn't we try to have lacinia follow the _spec_ on this one?

> We're gradually shifting to using with-warning (which is non-standard) to report processing errors that are recoverable, such as a failure accessing a 3rd party service.

Watch out, soon your clients will start failing if they see any warnings in extensions! :)

**Comment by hlship** [comment]
As far as I understand the spec, the `data` key is omitted if execution is unable to even begin (typically, a parse error of the GraphQL query itself).  In any other case where execution actually begins, the `data` key will be present, even if it is nil.

**Comment by kipz** [comment]
Is this a "won't-fix" then? Just wondering what the resolution was...

**Comment by brookeswanson** [comment]
Adding a link to the relevant section of the GraphQL spec for anyone else who happens upon this issue.

https://spec.graphql.org/June2018/#sec-Data

>The data entry in the response will be the result of the execution of the requested operation. If the operation was a query, this output will be an object of the schema’s query root type; if the operation was a mutation, this output will be an object of the schema’s mutation root type.
If an error was encountered before execution begins, the data entry should not be present in the result.
If an error was encountered during the execution that prevented a valid response, the data entry in the response should be null.
