### ISSUE TITLE
with-extensions does not seem to work for mutation

### ISSUE THREAD

**Issue by nimaai** [walmartlabs/lacinia#312]
Hi

I am trying to modify the extensions map for the result of a mutation using `with-extensions`, but it does not work:

https://github.com/leihs/leihs-borrow/blob/mk/master/src/all/leihs/borrow/resources/orders.clj#L167

The result is:

`{:data nil, :errors ({:message Non-nullable field was null., :locations [{:line 3, :column 5}], :path [:submitOrder :purpose]})}`

Where the value is `nil` and `:extensions` key is missing too.

If I simply return the value unwrapped (without `with-extensions`) then the `:data` value is not nil.

Thanks for help

**Comment by hlship** [comment]
I'll look into this.

**Comment by hlship** [comment]
Well, obviously I haven't looked into this.  Looks like that link is dead, so please re-open with new link or details.
