### ISSUE TITLE
Resolver mappings with namespaced keys don't compose

### ISSUE THREAD

**Issue by onetom** [walmartlabs/lacinia#313]
# Preface

During development we might want to work with both the EDN and GraphQL SDL representation of a schema. One reason could be that we want to check how some SDL representation looks like in EDN.

To minimize changes to our program, it would be nice if we can easily switch one schema definition style for the other.

# Problem

Depending on our input schema format, we need 2 different data structures for attaching resolvers.

1. For `attach-resolvers`
  a. `{:q-resolver q-resolver}`
  b. `{:namespaced/q-resolver q-resolver}`
2. For `parse-schema`:
  a. `{:QueryRoot {:q q-resolver}}`
  b. `{:QueryRoot {:q :q-resolver}}`
  c. `{:QueryRoot {:q :namespaced/q-resolver}}`

where `q-resolver` is a resolver function.

It is possible to use a simple, non-namespaced keyword instead of a function (2b instead of 2a),
which can be further transformed by 1a, hence it can be used in existing code in place of an EDN schema.

However, `parse-schema` throws this error when using the 2c form:

```
Arguments to parse-schema do not conform to spec:
:namespaced/q-resolver - failed: fn? in: [1 :resolvers :QueryRoot 1 :q 1] at: [:attachments :resolvers 1 1 :function :function] spec: :com.walmartlabs.lacinia.schema/function-or-var
:namespaced/q-resolver - failed: var? in: [1 :resolvers :QueryRoot 1 :q 1] at: [:attachments :resolvers 1 1 :function :var] spec: :com.walmartlabs.lacinia.schema/function-or-var
:namespaced/q-resolver - failed: simple-keyword? in: [1 :resolvers :QueryRoot 1 :q 1] at: [:attachments :resolvers 1 1 :keyword] spec: :com.walmartlabs.lacinia.parser.schema/field-fn
```

# Solution 1

Allow namespaced keywords in 
https://github.com/walmartlabs/lacinia/blob/ea9468d2f9d64286fbf64486b65b8b3f62225cb7/src/com/walmartlabs/lacinia/parser/schema.clj#L545-L546

# Solution 2

Restructure the API somehow and provide only 1 kind of mapping?

# Reproduction

```clojure
(use 'clojure.pprint)
(require '[com.walmartlabs.lacinia :as lacinia])
(require '[com.walmartlabs.lacinia.schema :as lacinia.schema])
(require '[com.walmartlabs.lacinia.parser.schema :as lacinia.parser.schema])

(def EDN-queries {:q {:type 'String :resolve :q-resolver}})
(def EDN-schema {:queries EDN-queries})
(def EDN-schema' {:objects {:QueryRoot {:fields EDN-queries}}})
(def SDL-schema "type QueryRoot {q: String}")

(defn q-resolver [_ _ _] "result of q")
(def EDN-resolvers {:q-resolver q-resolver})
(def SDL-resolvers {:QueryRoot {:q q-resolver}})

(defn with-EDN-resolvers [EDN-schema EDN-resolvers]
  (lacinia.util/attach-resolvers EDN-schema EDN-resolvers))

(defn with-SDL-resolvers [SDL-schema SDL-resolvers]
  (lacinia.parser.schema/parse-schema SDL-schema {:resolvers SDL-resolvers}))

(defn test-query [schema-with-resolvers]
  (-> schema-with-resolvers lacinia.schema/compile (lacinia/execute "{q}" nil nil)))

(pprint
 {:EDN (-> EDN-schema (with-EDN-resolvers EDN-resolvers) test-query)
  :EDN' (-> EDN-schema' (with-EDN-resolvers EDN-resolvers) test-query)
  :SDL-fn (-> SDL-schema (with-SDL-resolvers SDL-resolvers) test-query)

  ; Namespaced keywords are handled by `attach-resolvers`
  :EDN-ns-kw (-> EDN-schema
               (assoc-in [:queries :q :resolve] :namespaced/q-resolver)
               (with-EDN-resolvers {:namespaced/q-resolver q-resolver})
               test-query)

  :SDL-kw (-> SDL-schema 
            (with-SDL-resolvers {:QueryRoot {:q :q-resolver}})
            (with-EDN-resolvers EDN-resolvers)
            test-query)})

(try
  (-> SDL-schema
    (with-SDL-resolvers {:QueryRoot {:q :namespaced/q-resolver}}) 
    (with-EDN-resolvers {:namespaced/q-resolver q-resolver})
    test-query)
  (catch Throwable e
    (print (:cause (Throwable->map e)))))
```

Lacinia & Clojure version:
```edn
{:deps {
  org.clojure/clojure {:mvn/version "1.10.1"}
  com.walmartlabs/lacinia {:mvn/version "0.36.0-alpha-2"}}}
```

**Comment by onetom** [comment]
There is a similar issue with scalar handling too.

The the value for the `:scalars` key in the `attach` parameter of `parse-schema` expects this format:

```clojure
{:CustomScalarName {:serialize identity
              :parse identity}
```

while the `~` `attach-scalar-transformers`

**Comment by hlship** [comment]
If you follow the changes that have been happening in master, there's now more inject functions, such as inject-resolvers, in com.walmartlabs.lacinia.util, and this is a better unification of attaching parses that works well for both GraphQL schema documents and EDN schemas.

**Comment by hlship** [comment]
So, basically, use the 1-arity version of parse-schema, then supplement with inject-resolvers, inject-enum-transformers, etc.
