### ISSUE TITLE
 Feature request - add non-empty-list support

### ISSUE THREAD

**Issue by CHNB128** [walmartlabs/lacinia#325]
You already have `non-null` and `list` type, but this sentence don't mean that list shouldn't be empty
```
{:type '(non-null (list (non-null :String)))}
```  
So, it would be nice if we will have able to handle this case in parse step.

**Comment by CHNB128** [comment]
Would be nice do the same with `:String` type. Some thing like `:NonBlankString`.

**Comment by CHNB128** [comment]
https://github.com/walmartlabs/lacinia/pull/326

**Comment by CHNB128** [comment]
Made draft PR with base implementation of this feature: https://github.com/walmartlabs/lacinia/pull/326

**Comment by hlship** [comment]
This represents a concept that goes beyond the spec.  There wouldn't be a way to represent this kind of type signature in the GraphQL schema format.

You could add your own scalar for a non-blank String.

**Comment by hlship** [comment]
I'm sorry, but we won't be implementing this.
