### ISSUE TITLE
Feature Request: support apollo tracing format

### ISSUE THREAD

**Issue by coffeedoughnuts** [walmartlabs/lacinia#329]
Hi

I notice you have support for an experimental feature for side loading resolver timing data as an extension in the response. Would it be possible to add support (optional, if required) to have this timing data returned in a format compatible with Apollo Tracing. A lot of GraphQL tools use this format, including the popular GraphQL Playgrounds IDE/debugger and the various tools Apollo produce themselves. The format is detailed [here](https://github.com/apollographql/apollo-tracing) and seems quite close to what you already produce

**Comment by hlship** [comment]
I've considered this and will see if I can carve out some time. I'm not wedded to the current format, but haven't looked in detail at the Apollo format either.
