### ISSUE TITLE
Error despite of using tag-with-type

### ISSUE THREAD

**Issue by nimaai** [walmartlabs/lacinia#334]
Hi 

I am most probably missing some piece. I am tagging my values with `tag-with-type`, but still getting the error: `Field resolver returned an instance not tagged with a schema type.`.

This [commit](https://github.com/leihs/leihs-borrow/commit/8aff7e1d4cb889e2f6e9cfe8741d7f6c5d5d97d7) shows the interface and the sub-types and resolvers concerned. 

This is how I use `tag-with-type`: https://github.com/leihs/leihs-borrow/commit/8aff7e1d4cb889e2f6e9cfe8741d7f6c5d5d97d7#diff-99660cb1e7df7af4a7919c71d3ff1a56R29

Metadata of the returned map value seem also be correct: `{:com.walmartlabs.lacinia.schema/type-name :Pickup}`

Any help is greatly appreciated.

**Comment by hlship** [comment]
Can we see the exact exception, stack trace, version of lacinia, etc?

**Comment by nimaai** [comment]
There is no stack trace, as there is no exception. 

The error-map from the result is as follows:
```edn
{:errors ({:message Field resolver returned an instance not tagged with a schema type., :locations [{:line 2, :column 3}], :path [:visit], :extensions {:arguments {:id bc3c16f1-6592-55fe-919e-37746053000f}}}), :data nil}
```

The class of the resolved value is `clojure.lang.PersistentHashMap` with the above-mentioned metadata, so the respective place in lacinia seems to work correctly:https://github.com/walmartlabs/lacinia/blob/ae0a65a1e2fee58a4abf0b6ec49426f4bfd45561/src/com/walmartlabs/lacinia/schema.clj#L111

I see the type `Pickup` also in the GraphiQL browser displayed correctly as one of the implementations of the `Visit` interface. 

Lacinia version: `0.35.0`

**Comment by hlship** [comment]
Was there any resolution here?  I still don't see anything in your code that would cause the behavior you describe.

**Comment by nimaai** [comment]
Some of my resolver wrappers is messing with the meta data of the resolved value. Similar problem on the part of my codebase as in https://github.com/walmartlabs/lacinia/issues/349. Thanks.

**Comment by hlship** [comment]
I'm working on a blog post to elaborate on these kinds of problems.
