### ISSUE TITLE
Returning all errors on a mutation

### ISSUE THREAD

**Issue by mt3593** [walmartlabs/lacinia#337]
First off brilliant library, being using this for a while now.

As the title suggests I want to return all the errors on a mutation. Currently I only seem to get one error back, assume this is just the first error that we hit on the parsing of the mutation. Ideally I want to return each missing key in the errors list and each scalar conversion failure in the errors array.

**Comment by hlship** [comment]
I'm not sure what you're looking for here; if there's a _parse_ error, that ends the parsing phase, and the response map will have a `:errors` key but no `:data` key.

If there's errors during execution, (e.g., providing an error map to `(resolve-as ...)`) then you should get all of those; there isn't any logic that will stop execution of the second mutation after the first.

**Comment by hlship** [comment]
Please re-open if you have more details to share.

**Comment by mt3593** [comment]
Sorry was meant to get back to you but got moved onto other things. I think the issue is more our side than in this library, so apologies for any time wasted.
