### ISSUE TITLE
If null is returned for a non-null field it should propagate up to the first non-null parent

### ISSUE THREAD

**Issue by akmiller78** [walmartlabs/lacinia#341]
Per the graphql spec on [Errors and Nullability](https://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability), when a non-null field errors (or returns null) then the null value should be propagated up to the first nullable parent reached, or the data key if all parents are non-null.

Given the following code sample file:

```clojure
(ns lacinia-sample.core
  (:require [com.walmartlabs.lacinia.schema :as schema]
            [com.walmartlabs.lacinia :as lacinia]))

(def schema
  {:objects
   {:Employer
    {:fields
     {:id {:type '(non-null ID)
           :resolve (fn [_ _ {id :id}]
                      id)}
      :name {:type '(non-null String)
             :resolve (fn [_ _ {id :id}]
                        nil)}}}

    :User
    {:fields
     {:id {:type '(non-null ID)}
      :employer {:type :Employer}}}}

   :queries
   {:user {:type '(non-null :User)
           :args {:id {:type 'ID}}
           :resolve (fn [_ {id :id} _]
                      {:id "1"
                       :employer {:id "10"}})}}})


(defn query [graphql-query]
  (let [compiled-schema (schema/compile schema)]
    (lacinia/execute compiled-schema graphql-query nil nil)))
```

When queried with the following:

```graphql
{ user (id: "1")
  {
     id
     employer {
       id
       name
     }
   }
}
```

The actual result returned:

```clojure
{:data {:user {:id "1", :employer {:id "10", :name nil}}},
 :errors
 ({:message "Non-nullable field was null.",
   :locations [{:line 6, :column 12}],
   :path [:user :employer :name]})}
```

The expected result according to the graphql specification would be:

```clojure
{:data {:user {:id "1", :employer nil}},
 :errors
 ({:message "Non-nullable field was null.",
   :locations [{:line 6, :column 12}],
   :path [:user :employer :name]})}
```

This has caused issues for us in our current application because the client is getting invalid partial results back which is especially problematic when using a strongly typed client like TypeScript.

This has been tested on the latest official release `0.37.0` as well as `0.38.0-alpha5`.

**Comment by hlship** [comment]
The null handling has always been a bit dodgy; this is certainly something to get fixed.
