### ISSUE TITLE
Embedded examples missing from documentation

### ISSUE THREAD

**Issue by towler73** [walmartlabs/lacinia#346]
Hi, the embedded example are not longer showing in the documentation.  I looks like it might have started when you "upgraded to use Python3/Sphinx 3.2.1 for docs (incomplete)".  

I'm guessing something is wrong in the below script.
docs/_exts/remote.py

**Comment by hlship** [comment]
Damn. Thought I checked that.

**Comment by hlship** [comment]
I'd love to have the time to convert the docs to Antora.

**Comment by towler73** [comment]
> I'd love to have the time to convert the docs to Antora.

I'm not familiar with Antora.  I'll take a look if I get some time.

**Comment by hlship** [comment]
So, it builds fine locally for me, but is obviously not building on readthedocs so I'll see if there's a log file I can use to debug.

**Comment by hlship** [comment]
Got rid of my custom sphinx plugin and just copied the various sources over.
