### ISSUE TITLE
Latest clj-antlr release includes a stray call to println

### ISSUE THREAD

**Issue by sashton** [walmartlabs/lacinia#352]
Version 0.2.8 of `clj-antlr` includes what appears to be an accidental invocation of `println`.
Once https://github.com/aphyr/clj-antlr/pull/21 is merged and released, we should use the new version of `clj-antlr`.

**Comment by hlship** [comment]
Thanks for tracking that down; I noticed this as well and was concerned it was something in the Lacinia code.

**Comment by hlship** [comment]
Should not be a problem to downgrade to an earlier version of clj-antlr.

**Comment by hlship** [comment]
I've just updated to 0.2.9, which doesn't have this issue.
