### ISSUE TITLE
tutorial issues

### ISSUE THREAD

**Issue by mattford63** [walmartlabs/lacinia#364]
Hi, great tutorial!  I very much liked the style of it.  

A couple of comments:
- the component use doesn't seem idiomatic particularly the main page of component says not to add dependencies within components themselves (rather do so at system-map creation time)
- the latter stages of the tutorial had some bugs (or code changes not in the text).  I needed to update
* the cgg-shema, 
* the db creation (primary key and foreign key on ratings table)
* I couldn't get the $1 form of queries working vs ?.  
* Upserts need to be an execution.

A working version (for me at least) is here Please see this 

https://github.com/mattford63/lacinia-tutorial

each commit roughly following on with the tutorial stages.

**Comment by hlship** [comment]
Thanks for the help, I'll be looking into these issues. All good points.

Sorry for the *long* delay.
.
I'll consider some changes w.r.t. components and dependencies; At Walmart, we developed and use https://github.com/walmartlabs/schematic to manage component configuration and dependencies, but I don't want to introduce that into the tutorial.

**Comment by mattford63** [comment]
I think (can't quite be sure) that I did find an official code repo of the tutorial that has some of these things fixed.  That would be a better source of truth.  Those changes hadn't made it into the doc code examples though.

**Comment by hlship** [comment]
The process of getting code form the tutorial example app into the lacinia documentation is ... tortuous.

**Comment by hlship** [comment]
I've complete rewritten the tutorial as well as other documentation.
