### ISSUE TITLE
Resolver wrapper should not check for sequential for custom scalar types

### ISSUE THREAD

**Issue by brendanyounger** [walmartlabs/lacinia#38]
I added a custom JSON scalar type to my schema and I cannot return a JSON array because of the check for sequential values here: https://github.com/walmartlabs/lacinia/blob/d8cb65d812d4967e023c841faa0608905030de23/src/com/walmartlabs/lacinia/schema.clj#L414

While this is useful for debugging, it shouldn't be applied to custom scalar types.

**Comment by hlship** [comment]
We'll need to look into using type information to figure out whether to map the results or just use the single result.  Should not be impossible.

**Comment by hlship** [comment]
So you are returning a value, but it looks like an array to Lacinia, but you have a scalar for the value type such that it can be serialized into the response as is.  Right?

This is, to me, an odd edge case.

Could you wrap your JSON value in a wrapper that isn't a sequential, and have your :serializer extract the nested value?

**Comment by brendanyounger** [comment]
That is correct, I had a scalar JSON type that I was using which was sometimes an array.  I wound up wrapping it like you suggested as a work-around. I was just surprised by the error. 

It might help to have an example of this in the documentation to clarify when the :serializer functions are run.

**Comment by hlship** [comment]
I think this is a wont/cant fix.
