### ISSUE TITLE
`type` on an `ArgumentDef` that refers to an input object always returns `nil`

### ISSUE THREAD

**Issue by robhanlon22** [walmartlabs/lacinia#395]
Since input objects don't satisfy the TypeDef protocol and are instead stored as plain maps in the schema, calling `type` on an `ArgumentDef` that refers to an input object always returns `nil`.

Additionally, since the input objects aren't wrapped with a record, the selections API does not work against them, leading to inconsistency of access.

**Comment by hlship** [comment]
I'm looking into this, but at first glance, Object and InputObject are handled identically, by the same code.

**Comment by hlship** [comment]
Ah, yes, differences in `compile-type`.
