### ISSUE TITLE
version out of date?

### ISSUE THREAD

**Issue by justin-roche** [walmartlabs/lacinia#397]
The tutorial gives the dependency [com.walmartlabs/lacinia "0.21.0"]. 

This caused an error for me:

```
Syntax error (IllegalArgumentException) compiling deftype* at (flatland/ordered/set.clj:19:1).
Must hint overloaded method: toArray
```

To resolve it I had to upgrade to the current version [com.walmartlabs/lacinia "1.1-alpha-6"]

**Comment by hlship** [comment]
We had a great contribution, #400, that updated the version numbers recently.
