### ISSUE TITLE
"Resolver specified in schema not provided" could be clearer

### ISSUE THREAD

**Issue by vemv** [walmartlabs/lacinia#401]
The error message thrown by https://github.com/walmartlabs/lacinia/blob/0c4976e494461b6052f2e211b18e9eb4d3f48bcd/src/com/walmartlabs/lacinia/util.clj#L45 could be a little clearer.

Perhaps?

```diff
-Resolver specified in schema not provided.
+The resolver that has been specified in the schema has not been provided.
```

Or perhaps one could go the extra mile and make the message a bit more dynamic:

```diff
-Resolver specified in schema not provided.
+The resolver (`:my/mutation`) that has been specified in the schema has not been provided. Is there code that registers `:my/mutation`?
```

wdyt?

Cheers - V

**Comment by hlship** [comment]
I'll think about it; I obviously use Pretty (https://github.com/AvisoNovate/pretty) so I'm used to seeing the exception info map along with the message, so I prefer for the message to not be redundant.

**Comment by vemv** [comment]
What was the issue's resolution?

It's not that redundant to show a diagnostic in the message. Under my reloaded workflow this is all I see initially after a failed `(reset)`:

```
Execution error (ExceptionInfo) at com.walmartlabs.lacinia.util/attach-callbacks$fn (util.clj:45).
Resolver specified in schema not provided.
```

I can type `(.printStackTrace *e)`, sure, but that's more steps to type/remember. Also for many cases I don't particularly need the whole stacktrace, simply a diagnostic would give me all I need and save the scanning through noise.
