### ISSUE TITLE
io.aviso.pretty dependency

### ISSUE THREAD

**Issue by lxsli** [walmartlabs/lacinia#410]
With Lacinia 1.1:

   $ lein uberjar
   Compiling user-api.auth
   Compiling user-api.errors
   Compiling user-api.features
   Compiling user-api.filters
   Compiling user-api.graphql
   Syntax error macroexpanding at (trace.clj:15:1).
   Execution error (FileNotFoundException) at com.walmartlabs.lacinia.trace/loading (trace.clj:15).
   Could not locate io/aviso/exception__init.class, io/aviso/exception.clj or io/aviso/exception.cljc on classpath.
   
   Full report at:
   /tmp/clojure-14195317407193967353.edn
   Compilation failed: Subprocess failed (exit code: 1)

Adding a dependency on `[io.aviso/pretty "1.1.1"]` fixed the issue.

**Comment by nottmey** [comment]
I can reproduce this issue and the fix also resolved it for me. Thanks for the hint, saved me some time!

(Context: openjdk/17.0.2 clojure/1.10.3 lacinia/1.1)

**Comment by hlship** [comment]
This was fixed by e2a0da69f1b31b947b1245d8071601ad9ee3d84b, however, it was only ever a dev dependency, so I'm not sure how this affected you.
