### ISSUE TITLE
Question: Is there a way to return JSON without a corresponding EDN definition?

### ISSUE THREAD

**Issue by ejstembler** [walmartlabs/lacinia#423]
I have a Postgres function which returns nested JSON. Is there a way to return the JSON without a corresponding EDN definition?

**Comment by hlship** [comment]
Yes, you can define a scalar type that is a JSON object.

**Comment by ejstembler** [comment]
@hlship Thanks for the reply! That sounds encourging.

Though, admittendly I have no clue what is needed to get it to work. Do you have a link to documention which can point me in the right direction? Or, some small snippet of example code?

I tried looking at the [scalar_tests.clj](https://github.com/walmartlabs/lacinia/blob/master/test/com/walmartlabs/lacinia/scalar_tests.clj) unit tests, however, I didn't see anything JSON-related there...

**Comment by hlship** [comment]
This should go into an FAQ as it has come up before.  I'll see about adding docs and/or test to demonstrate.
