### ISSUE TITLE
Use of executor/selection in streamer functions

### ISSUE THREAD

**Issue by happy-river** [walmartlabs/lacinia#426]
I'm not sure if this is a `lacinia` issue or a `lacinia-pedestal` issue, but I suspect the former.  When resolver functions are called, `:com.walmartlabs.lacinia/selection` is set in the context so they can use `executor/selection`, but when a streamer function is called, it is not set.

I'm currently working around this in my use of `lacinia-pedestal` by adding an interceptor that calls `executor/parsed-query->context` to my list of subscription interceptors, but it seems like it ought to be the responsibility of one or the other of the libraries.  I'd be happy to work on a PR for it if you could give me some guidance on where it ought to go.

**Comment by hlship** [comment]
This seems like a bug to me too, but let me think about it and check the code first.
