### ISSUE TITLE
Question: Query complexity and depth

### ISSUE THREAD

**Issue by syunta** [walmartlabs/lacinia#450]
Hello. I'm using lacinia.

I was wondering if there is a way to quantify the Query Complexity as a cost in lacinia.
By measuring the complexity of queries beforehand, I could protect the application from high-cost queries.
 I'm open to any method, whether it's an automatic calculation or a manual assignment of costs.

Also, if there are any other suitable approaches for lacinia, I'd love to hear about them.

Thank you!

**Comment by hlship** [comment]
This is something that can be addressed somewhat using the preview API, which gives you a view of the entire query.  Identifying cost is tricky however ... it's very application specific.

**Comment by syunta** [comment]
Thank you for your response. I've decided to also use Persisted Queries to prevent unexpectedly executing complex and high-cost queries.
