### ISSUE TITLE
Fields are not merged

### ISSUE THREAD

**Issue by gusbicalho** [walmartlabs/lacinia#52]
This query:
```graphql
query { 
  viewer { 
    login
  }
  viewer {
    databaseId
  }
}
```

Should return something like:
```edn
{:data {:viewer {:login "someone" :id "qwertyuiop"}}}
```

Instead, it returns only the `databaseId`. If we query for the login last, it returns just the login.

**Comment by hlship** [comment]
I'll have to check the spec and/or reference implementation to see if this is covered.  I suspect this is a case that should be flagged as an illegal request (multiple top-level operations with the same name/alias).

**Comment by thorstadt** [comment]
I believe this should result in an error.

**Comment by gusbicalho** [comment]
It works if you try it on the textareas in the graphql tutorial http://graphql.org/learn/queries/
```graphql
{
  hero {
    name
  }
  hero {
    id
  }
}
```

also on the github explorer https://developer.github.com/early-access/graphql/explorer/ (with the query on the OP)

**Comment by bcarrell** [comment]
Yup, it's legit.  This should be fixed.
