### ISSUE TITLE
Add ability to decorate resolver functions

### ISSUE THREAD

**Issue by hlship** [walmartlabs/lacinia#58]
A certain useful class of problems can be solved by passing field resolver functions through a set of middleware before being employed in a schema; this would allow for such things as authentication/authorization checks, implicit logging, tracing, and other common use-cases.

I would suggest a signature as follows:

     (middleware object-name field-name f) => f'

The object-name and field-name are keywords.  The function is as provided in the input schema, and the result is the same or a decorated resolver function.

**Comment by hlship** [comment]
Another common use case is converting a core.async channel, or a Manifold deferred, into a Lacinia ResolverResult.

**Comment by stijnopheide** [comment]
Maybe middleware (as in ring middleware) is a bad name. Since results of resolver functions can be asynchronous would it not be better to use `interceptor` like in pedestal / yada?

Related to that, how would a user define an interceptor that also can handle async results of the resolver function f?

**Comment by hlship** [comment]
Want to keep whatever we do very, very simple. A function that decorates a raw resolver function into a smarter resolver function would do the trick.  There's nothing that says you can't use an interceptor as part of the implementation of your field resolver, but we want to avoid too much machinery or magic (and there's already a bit!).

**Comment by stijnopheide** [comment]
this is really good! thank you.

**Comment by heneryville** [comment]
This was removed in #85 . Presumably b/c the same work can be done by transforming the input to attach-resolvers in application code.

**Comment by hlship** [comment]
Absolutely, though in the current alpha release there's some support for decorating functions based on the presence of directives on the field.
