### ISSUE TITLE
application/graphql not supported despite what README says

### ISSUE THREAD

**Issue by sbgreene1307** [walmartlabs/lacinia#76]
In the README it clearly states, 

> User queries are provided as the body of a request with the content type application/graphql. It looks a lot like JSON.

However, this wasn't the case and actually causes a validation failure at [lacinia#L85](https://github.com/walmartlabs/lacinia/blob/master/src/com/walmartlabs/lacinia.clj#L85) when you setup the example to use the application/graphql MIME type.

Was the README bit meant for lacinia-pedestal? Very confusing.

If I am missing something with the implementation please let me know.

Thanks in advance!

**Comment by bcarrell** [comment]
Hey, thanks for the report.

Can you clarify what you mean here?  There's nothing in this library that would enforce any `Content-Type`.  The parameter that you linked to looks correct.  Should this issue be filed for `pedestal-lacinia`?

I definitely agree that there's some parts of the README that should be revised, though.  Help is welcome on that one!

**Comment by hlship** [comment]
I'm closing this issue; please re-open if you have more information.  Note that there's been some significant upgrades to the documentation of lacinia-pedestal of late.
