### ISSUE TITLE
Documentation for `execute` `variables` parameter is unclear

### ISSUE THREAD

**Issue by noprompt** [walmartlabs/lacinia#87]
The documentation for the `variables` parameter of `com.walmartlabs.lacinia/execute` says

> compile-time variables that can be referenced inside the query using the `$variable-name` production.

which is not very helpful. My coworker and I attempted to recover the expected value type information by navigating the passage of `variables` through the code but after digging all the way down to `com.walmartlabs.lacinia.parser/compute-arguments` we decided to open an issue instead.

It would be nice to see either or even both of `:pre`/`:post` conditions or specs for not only this particular function, but public functions this library exposes in general.

**Comment by noprompt** [comment]
FWIW we took a look at the tests and managed to figure out that it was supposed to be a map. It also turned out that we had our query written wrong and the error message confused us. We discovered all of this via the test suite — arguably _not_ documentation.

Though we've discovered our mistake it still seems like a good idea to have a better description of the expected argument types to public functions in the forms I mentioned above. The README actually has `(execute schema "...query..." nil nil)` but I think those `nil`s would be better served by their empty counterparts `{}` and `{}`.

Are the maintainers of this library open to these kinds of patches which may help alleviate confusion like this in the future?

**Comment by bcarrell** [comment]
Hey, thanks for the report!

To address your last bit first, we would absolutely welcome any PRs along these lines, or any PR in general.  If it's larger work, probably best to discuss first so everyone's on the same page, but if it's smaller work (along the lines of what you suggest), go ahead and send it and we'll likely merge it really quickly.

I agree that documentation is always an issue we work on and this particular fn could be better described and enforced, either through `:pre`/`:post` or `spec` as you mentioned.  Thanks for pointing it out and sorry for the hardship. ☹️

**Comment by noprompt** [comment]
@bcarrell Thanks for understanding. Now that I know PRs of this nature are welcomed I'll get something together for review. Much appreciated!
