### ISSUE TITLE
Schema compiler should enforce that field and entity names are properly formed

### ISSUE THREAD

**Issue by AngryGami** [walmartlabs/lacinia#88]
For example:
`(execute my-schema "queryname { some-field-with-dashes }" nil nil)`
return following error:
`extraneous input '-' expecting {'(', '{', '}', '...', '@', Name}`

While my schema allow me to have fields with dashes - i.e. this is only query time issue. I managed to track this down to file: `com\walmartlabs\lacinia\Graphql.g4` line 152
```
Name
    : [_A-Za-z][_0-9A-Za-z]*
    ;
```

I think this regexp should look like this rather:
```
Name
    : [_A-Za-z-][_0-9A-Za-z-]*
    ;
```
i.e. allow dash as part of field name.

**Comment by bcarrell** [comment]
Hey!  Unfortunately, this isn't valid as per the [GraphQL specification](http://facebook.github.io/graphql/#sec-Names).  That's the reasoning behind not allowing dashes as part of the field name.

**Comment by AngryGami** [comment]
Hm... I agree, though when I compile schema like this:
```
{:objects {
  :my-object-with-dashes {
    :field-with-dashes {:type String}}}}
```
I got no warnings or errors from Lacinia.

**Comment by bcarrell** [comment]
Right, I agree, we should probably not allow that and fail during schema compilation.
