### ISSUE TITLE
Required vs optional query arguments 

### ISSUE THREAD

**Issue by JayAndCatchFire** [walmartlabs/lacinia#98]
Is there a way to specify in the edn schema whether arguments to a query (or mutation or subscription) are required or optional? If not, could there be? 

What's the currently preferred method of handling missing arguments?

**Comment by bcarrell** [comment]
Hi!  The way to mark arguments as required would be to declare the type as non-nullable.  This should throw an error if the argument is not supplied.  If a type isn't declared as non-nullable and isn't passed during the query, it won't be part of the `args` map in the resolve fn.  You can also set these to a default-value if you wish.

Does that help?  Let me know if you need examples or further explanation.

**Comment by JayAndCatchFire** [comment]
Excellent!  I was hoping that was the case, but there was no mention of that use case anywhere I could find in the documentation.

Thank you!

**Comment by bcarrell** [comment]
Thanks for the feedback -- I'll try and make this more clear in the documentation.
