### ISSUE TITLE
Example of authentication, viewer pattern?

### ISSUE THREAD

**Issue by JayAndCatchFire** [walmartlabs/lacinia#99]
I'm interested in implementing a viewer authentication pattern like what's described in these posts:
https://dev-blog.apollodata.com/a-guide-to-authentication-in-graphql-e002a4039d1
https://medium.com/the-graphqlhub/graphql-and-authentication-b73aed34bbeb

I'm having trouble figuring out how I'd handle nested nodes/queries like that using lacinia.  How would I model something like that in the edn?

**Comment by hlship** [comment]
Inside lacinia-pedestal, we purposely break things up into several stages, or Pedestal interceptors.  This is to make it reasonable to insert your own interceptors into the mix, and there is API that, given the parsed query, can identify what the referenced operations are.  With that in place, you can perform authorization checks before even starting to execute the GraphQL query.

This is something that could be discussed in more detail in the lacinia-pedestal manual.

I would suggest creating a new issue there to further discussion.

**Comment by JayAndCatchFire** [comment]
Thanks for the heads-up.  I didn't think to look at the lacinia-pedestal project since I'm not using it in my project.

I'll take a look over there and make a new issue on that project if I don't find what I'm looking for.

Thank you!
